language: go

# we use :443 in tests
sudo: required

os:
  - linux
  - osx

env:
  - TRAVIS_GO_VERSION=1.9.4 GRAMEWORK_SHORT=1
  - TRAVIS_GO_VERSION=1.9.5 GRAMEWORK_SHORT=1
  - TRAVIS_GO_VERSION=1.9.6 GRAMEWORK_SHORT=1
  - TRAVIS_GO_VERSION=1.9.x GRAMEWORK_SHORT=0
  - TRAVIS_GO_VERSION=1.10.1 GRAMEWORK_SHORT=1
  - TRAVIS_GO_VERSION=1.10.2 GRAMEWORK_SHORT=1
  - TRAVIS_GO_VERSION=1.10.x GRAMEWORK_SHORT=0
  - TRAVIS_GO_VERSION=tip GRAMEWORK_SHORT=1 TRAVIS_ALLOW_FAILURE=1

matrix:
  fast_finish: true

before_install:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get -t -v ./...
  - go get -v github.com/golang/lint/golint
  - go get -v honnef.co/go/tools/cmd/megacheck
  - go get -v github.com/fzipp/gocyclo
  - go get -v golang.org/x/tools/cmd/goimports

script:
  # fail if a .go file hasn't been formatted with goimports
  - test -z $(goimports -l $GO_FILES)
  # check if it even compiles
  - go build
  # run the official Go static analyzer
  - go vet .
  # run all our tests with race detector and coverage analyzer enabled
  - ./.test.sh
  # "go vet on steroids" + linter
  - megacheck ./...
  # forbid code with huge functions
  - gocyclo -over 50 $GO_FILES
  # one last linter
  - golint -set_exit_status $(go list ./...)

after_success:
  - bash <(curl -s https://codecov.io/bash)
